const MATCH_STATUS = { //0-19
  NOT_STARTED: 0,
  FINAL: 1,
  DELAYED: 2,
  CANCELLED: 3,
  OTHER: 4,
  INTERRUPTED: 5
};

export const FOOTBALL_MATCH_STATUS = { //20-39
  ...MATCH_STATUS,
  FIRST_HALF: 20,
  HALFTIME: 21,
  SECOND_HALF: 22,
  AWAITING_EXTRA_TIME: 23,
  FIRST_EXTRA_TIME: 24,
  HALFTIME_EXTRA_TIME: 25,
  SECOND_EXTRA_TIME: 26,
  FINAL_EXTRA_TIME: 27,
  AWAITING_PENALTIES: 28,
  PENALTIES: 29,
  FINAL_PENALTIES: 30
};

export const AMERICAN_FOOTBALL_MATCH_STATUS = { //40-59
  ...MATCH_STATUS,
  FIRST_QUARTER: 40,
  END_FIRST_QUARTER: 41,
  SECOND_QUARTER: 42,
  HALFTIME: 43,
  THIRD_QUARTER: 44,
  END_THIRD_QUARTER: 45,
  FOURTH_QUARTER: 46,
  AWAITING_OVERTIME: 47,
  OVERTIME: 48,
  FINAL_OVERTIME: 49
};
