const MATCH_STATUS = {
  NOT_STARTED: 0,
  FINAL: 1,
  DELAYED: 2,
  CANCELLED: 3,
  OTHER: 4
};

export const FOOTBALL_MATCH_STATUS = {
  ...MATCH_STATUS,
  FIRST_HALF: 20,
  HALFTIME: 21,
  SECOND_HALF: 22,
  FIRST_HALF_OVERTIME: 23,
  HALFTIME_OVERTIME: 24,
  SECOND_HALF_OVERTIME: 25,
  FINAL_OVERTIME: 26,
  AWAITING_PENALTIES: 27,
  PENALTIES: 28,
  FINAL_PENALTIES: 29
};

export const AMERICAN_FOOTBALL_MATCH_STATUS = {
  ...MATCH_STATUS,
  FIRST_QUARTER: 40,
  END_FIRST_QUARTER: 41,
  SECOND_QUARTER: 42,
  END_SECOND_QUARTER: 43, //Same status as below
  HALFTIME: 43, //Same status as above
  THIRD_QUARTER: 44,
  END_THIRD_QUARTER: 45,
  FOURTH_QUARTER: 46,
  END_FOURTH_QUARTER: 47,
  OVERTIME: 48,
  FINAL_OVERTIME: 49
};
