export const MATCH_STATUS = {
  NOT_STARTED: 0,
  FINAL: 1,
  DELAYED: 2,
  CANCELLED: 3,
  OTHER: 4
};

export const FOOTBALL_MATCH_STATUS = {
  ...MATCH_STATUS,
  FIRST_HALF: 20,
  HALFTIME: 21,
  SECOND_HALF: 22,
  FIRST_HALF_OVERTIME: 23,
  AWAITING_OVERTIME: 24,
  HALFTIME_OVERTIME: 25,
  SECOND_HALF_OVERTIME: 26,
  FINAL_OVERTIME: 27,
  AWAITING_PENALTIES: 28,
  PENALTIES: 29,
  FINAL_PENALTIES: 30
};

export const AMERICAN_FOOTBALL_MATCH_STATUS = {
  ...MATCH_STATUS,
  FIRST_QUARTER: 40,
  END_FIRST_QUARTER: 41,
  SECOND_QUARTER: 42,
  HALFTIME: 43,
  THIRD_QUARTER: 44,
  END_THIRD_QUARTER: 45,
  FOURTH_QUARTER: 46,
  END_FOURTH_QUARTER: 47,
  OVERTIME: 48,
  FINAL_OVERTIME: 49
};

export const LABELS = {
  [MATCH_STATUS.NOT_STARTED]: '',
  [MATCH_STATUS.FINAL]: 'Fim',
  [MATCH_STATUS.DELAYED]: 'Adiado',
  [MATCH_STATUS.CANCELLED]: 'Canc',
  [MATCH_STATUS.OTHER]: 'Outro',
  [FOOTBALL_MATCH_STATUS.FIRST_HALF]: '1T',
  [FOOTBALL_MATCH_STATUS.HALFTIME]: 'Int',
  [FOOTBALL_MATCH_STATUS.SECOND_HALF]: '2T',
  [FOOTBALL_MATCH_STATUS.FIRST_HALF_OVERTIME]: '1TE',
  [FOOTBALL_MATCH_STATUS.HALFTIME_OVERTIME]: 'Int TE',
  [FOOTBALL_MATCH_STATUS.SECOND_HALF_OVERTIME]: '2TE',
  [FOOTBALL_MATCH_STATUS.FINAL_OVERTIME]: 'Fim TE',
  [FOOTBALL_MATCH_STATUS.AWAITING_PENALTIES]: 'Pen',
  [FOOTBALL_MATCH_STATUS.PENALTIES]: 'Pen',
  [FOOTBALL_MATCH_STATUS.FINAL_PENALTIES]: 'Fim Pen',
  [AMERICAN_FOOTBALL_MATCH_STATUS.FIRST_QUARTER]: '1Q',
  [AMERICAN_FOOTBALL_MATCH_STATUS.END_FIRST_QUARTER]: 'Fim 1Q',
  [AMERICAN_FOOTBALL_MATCH_STATUS.SECOND_QUARTER]: '2Q',
  [AMERICAN_FOOTBALL_MATCH_STATUS.HALFTIME]: 'HT',
  [AMERICAN_FOOTBALL_MATCH_STATUS.THIRD_QUARTER]: '3Q',
  [AMERICAN_FOOTBALL_MATCH_STATUS.END_THIRD_QUARTER]: 'Fim 3Q',
  [AMERICAN_FOOTBALL_MATCH_STATUS.FOURTH_QUARTER]: '4Q',
  [AMERICAN_FOOTBALL_MATCH_STATUS.END_FOURTH_QUARTER]: 'Fim 4!',
  [AMERICAN_FOOTBALL_MATCH_STATUS.OVERTIME]: 'OT',
  [AMERICAN_FOOTBALL_MATCH_STATUS.FINAL_OVERTIME]: 'Fim OT'
};

export const STOPPED_GAME = [
  MATCH_STATUS.NOT_STARTED,
  MATCH_STATUS.FINAL,
  MATCH_STATUS.DELAYED,
  MATCH_STATUS.CANCELLED,
  MATCH_STATUS.OTHER,
  FOOTBALL_MATCH_STATUS.HALFTIME,
  FOOTBALL_MATCH_STATUS.AWAITING_OVERTIME,
  FOOTBALL_MATCH_STATUS.HALFTIME_OVERTIME,
  FOOTBALL_MATCH_STATUS.FINAL_OVERTIME,
  FOOTBALL_MATCH_STATUS.AWAITING_PENALTIES,
  FOOTBALL_MATCH_STATUS.FINAL_PENALTIES,
  AMERICAN_FOOTBALL_MATCH_STATUS.END_FIRST_QUARTER,
  AMERICAN_FOOTBALL_MATCH_STATUS.HALFTIME,
  AMERICAN_FOOTBALL_MATCH_STATUS.END_THIRD_QUARTER,
  AMERICAN_FOOTBALL_MATCH_STATUS.END_FOURTH_QUARTER,
  AMERICAN_FOOTBALL_MATCH_STATUS.FINAL_OVERTIME
];
