name: 🔨 Build & 🧪 Test
on:
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2

      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Linting
        run: npm run lint

      - name: 🧪 Test
        run: CI='' npm run test:ci

      - name: 🔨 Build Static Storybook
        run: npm run build-storybook

      - name: 📂 Sync files to server (components.omegafox.me)
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.server }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          local-dir: ./storybook-static/
          server-dir: components.omegafox.me/
